version: "3.7"

services:
  zygo:
    image: senthilsweb/zygo:latest
    container_name: zygo
    networks:
      - backend
    restart: unless-stopped
    tty: true
    ports:
      - "3333:3000"
    environment:
      - API_SECRET=''
      - SLACK_TOKEN=xoxb-2804485819572-2885075919860-wmT1MfVDCGAAf48K27HFpbyf
      - SLACK_CHANNEL=C02RS31JTFG
      - REDIS_URI=rediss://:b3cd263ba8f14f32b7dee9907577d089@us1-deciding-kodiak-34245.upstash.io:34245
networks:
  backend: